### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by andcbii** [primetime43/GAPS-2#2] opened 2023-06-27 20:57 UTC
Any change you will create a docker image for this?

**Comment by primetime43** [comment] 2023-06-28 02:28
> Any change you will create a docker image for this?

I could look into how it’s done. Honestly, I’ve never created a docker image, so we’ll see if I’m able.

**Comment by primetime43** [comment] 2023-07-06 01:46
@andcbii Go ahead and try to create a docker image with this release. I've added some notes in the read me about creating it. I was able to get it running off the docker image/container myself with this.

https://github.com/primetime43/GAPS-2/releases/tag/v1.0.1

**Comment by primetime43** [comment] 2023-07-06 01:51
Seems all of the files are being packed or used in the container, im not sure. It loads the program and html etc, but seems its not being able to use/find the JS file

**Comment by primetime43** [comment] 2023-07-08 03:12
Ok, it seems most functionality is there. The issue is with linking the plex account with the plex api. Working on the issue...

**Comment by primetime43** [comment] 2023-07-09 07:40
Issue fixed in v1.0.2

**Closed by primetime43** 2023-07-09 07:40 UTC
Labels: enhancement

**Comment by andcbii** [comment] 2023-07-09 20:14
Where did you upload the docker image? I'm not able to pull it.

**Comment by primetime43** [comment] 2023-07-09 21:36
> Where did you upload the docker image? I'm not able to pull it.

I didnt upload an image. I wrote in the readme how to create the docker image yourself. I'll create an image eventually for ppl to download. This should be good for now to run and use it.

https://github.com/primetime43/GAPS-2#docker

**Comment by primetime43** [comment] 2023-07-21 01:03
@andcbii I've created a docker image, if you'd like to give it a try and let me know how it goes.

https://hub.docker.com/repository/docker/primetime43/gaps-2/general
